[package]
name = "printer"
description = "A simple Charms app"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
charms-sdk = { version = "0.8.0" }

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
